version: 0.2

# CodeBuild spec for building and packaging SAM Lambda application
# This file packages the Lambda code for deployment via CodePipeline
# DO NOT use 'sam deploy' - deployment will be handled by CloudFormation in CodePipeline

env:
  variables:
    # AWS Region
    AWS_REGION: ap-south-1
    # S3 bucket for packaged artifacts
    S3_BUCKET: webproject-builds
    # Project name
    PROJECT_NAME: webproject
    # CloudFormation stack name
    STACK_NAME: webproject-uploads-stack

phases:
  install:
    commands:
      - echo "=== INSTALL PHASE ==="
      - echo "Installing AWS SAM CLI and dependencies..."
      - pip install --upgrade pip
      - pip install aws-sam-cli
      - echo "Verifying AWS SAM version..."
      - sam --version
      - echo "AWS CLI is included with AWS SAM CLI"
      - aws --version
  
  pre_build:
    commands:
      - echo "=== PRE-BUILD PHASE ==="
      - echo "Current working directory:"
      - pwd
      - echo "Listing directory contents:"
      - ls -la
      - echo "Checking SAM template..."
      - test -f sam-template.yaml && echo "✓ sam-template.yaml found" || echo "✗ sam-template.yaml NOT found"
      - echo "Validating SAM template..."
      - sam validate --template sam-template.yaml --region ${AWS_REGION}
      - echo "✓ SAM template validation passed"
      - echo "Installing Lambda function dependencies..."
      - |
        if [ -f lambda/requirements.txt ]; then
          echo "Found Python requirements.txt"
          pip install -r lambda/requirements.txt -t lambda/
        fi
      - |
        if [ -f lambda/package.json ]; then
          echo "Found Node.js package.json"
          cd lambda && npm install && cd ..
        fi
  
  build:
    commands:
      - echo "=== BUILD PHASE ==="
      - echo "Running tests (optional)..."
      - |
        if [ -f tests/test.js ]; then
          echo "Running JavaScript tests..."
          npm test
        else
          echo "No test files found - skipping tests"
        fi
      - echo "Building SAM application..."
      - sam build --template sam-template.yaml
      - echo "✓ SAM build completed"
      - echo "Checking build output..."
      - ls -la .aws-sam/build/ 2>&1 || echo "Build directory not found"
      - test -f .aws-sam/build/template.yaml && echo "✓ template.yaml exists" || echo "✗ template.yaml NOT found"
  
  post_build:
    commands:
      - echo "=== POST-BUILD PHASE ==="
      - echo "Current directory: $(pwd)"
      - echo "Checking for SAM build template..."
      - |
        if [ ! -f .aws-sam/build/template.yaml ]; then
          echo "✗ ERROR: .aws-sam/build/template.yaml not found"
          echo "Listing current directory:"
          ls -la
          echo "Checking .aws-sam directory:"
          find .aws-sam -type f 2>/dev/null | head -20
          exit 1
        fi
      - echo "✓ SAM build template found"
      - echo "Packaging SAM application..."
      - |
        sam package \
          --template-file .aws-sam/build/template.yaml \
          --s3-bucket ${S3_BUCKET} \
          --s3-prefix "builds/$(date +%Y%m%d-%H%M%S)" \
          --region ${AWS_REGION} \
          --output-template-file packaged.yaml 2>&1
      - echo "✓ SAM package completed"
      - echo "Verifying packaged.yaml was created..."
      - |
        if [ -f packaged.yaml ]; then
          echo "✓ packaged.yaml created successfully ($(wc -c < packaged.yaml) bytes)"
          echo "First 30 lines of packaged.yaml:"
          head -30 packaged.yaml
        else
          echo "✗ ERROR: packaged.yaml was NOT created"
          exit 1
        fi

artifacts:
  name: SAMPackageArtifacts
  files:
    - packaged.yaml
  discard-paths: yes

cache:
  paths:
    - '/root/.cache/pip/**/*'

reports:
  CodeBuildReport:
    files:
      - packaged.yaml
    discard-paths: yes
    name: PackagedTemplate
