AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 Instances and Security Groups - Creates EC2 instances (Bastion, Public, Private, DB) with security groups in existing VPC'

Parameters:
  ProjectName:
    Type: String
    Description: Project name to be used as a prefix for all resource names
    Default: WebProject
    AllowedPattern: ^[a-zA-Z0-9-]+$
    ConstraintDescription: Project name must contain only alphanumeric characters and hyphens

  MyIpAddress:
    Type: String
    Description: Your IP address for SSH access (e.g., x.x.x.x/32)
    AllowedPattern: ^(\d{1,3}\.){3}\d{1,3}/\d{1,2}$
    ConstraintDescription: Must be a valid IP CIDR range (e.g., 1.2.3.4/32)

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Key Pair for SSH access to instances

  VpcStackName:
    Type: String
    Description: Name of the CloudFormation stack that created the VPC infrastructure
    Default: WebProject-network

  ResourcesName:
    Type: String
    Description: Prefix for resource names created in the VPC stack
    Default: WebProject  

  IamRoleStackName:
    Type: String
    Description: Name of the CloudFormation stack that created the ReadAccessRoleS3 IAM role
    Default: ReadAccessRoleS3

  AmazonLinux2AmiId:
    Type: String
    Description: AMI ID for the EC2 instances
    Default: 'ami-05fb2447d4d3d2610'

Resources:
  # Security Group 1 - Allow SSH from My IP
  SecGr1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-SecGr1'
      GroupDescription: Allow SSH from my IP
      VpcId:
        Fn::ImportValue: !Sub '${ResourcesName}-VPC-Id'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIpAddress
          Description: SSH access from my IP
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-SecGr1'

  # Security Group 2 - Allow HTTP/HTTPS from anywhere
  SecGr2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-SecGr2'
      GroupDescription: Allow HTTP/S from anywhere
      VpcId:
        Fn::ImportValue: !Sub '${ResourcesName}-VPC-Id'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: HTTP access from anywhere
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: HTTPS access from anywhere
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-SecGr2'

  # Security Group 3 - Allow all traffic from instances in this group
  SecGr3:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-SecGr3'
      GroupDescription: Allow all traffic from instances in this group
      VpcId:
        Fn::ImportValue: !Sub '${ResourcesName}-VPC-Id'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-SecGr3'

  # Self-referencing ingress rule for SecGr3
  SecGr3SelfReferenceRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecGr3
      IpProtocol: -1
      SourceSecurityGroupId: !Ref SecGr3
      Description: Allow all traffic from instances in this security group

  # IAM Instance Profile for EC2 instances with S3 read access
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${ProjectName}-EC2-S3ReadAccess-Profile'
      Roles:
        - Fn::ImportValue: ReadAccessRoleS3

  # Bastion Host - Public Subnet B
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Ref AmazonLinux2AmiId
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref EC2InstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref SecGr1
            - !Ref SecGr3
          SubnetId:
            Fn::ImportValue: !Sub '${ResourcesName}-PublicSubnet-B-Id'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-Bastion'

  # Public Application Instance - Public Subnet A
  PublicInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Ref AmazonLinux2AmiId
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Update system packages
          yum update -y
          
          # Install Apache web server
          yum install -y httpd
          
          # Start and enable Apache
          systemctl start httpd
          systemctl enable httpd
          
          # Create a simple index.html page
          cat > /var/www/html/index.html <<'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>${ProjectName} - Public Application</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      max-width: 800px;
                      margin: 50px auto;
                      padding: 20px;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      color: white;
                  }
                  .container {
                      background: rgba(255, 255, 255, 0.1);
                      backdrop-filter: blur(10px);
                      border-radius: 10px;
                      padding: 30px;
                      box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
                  }
                  h1 { color: #fff; margin-top: 0; }
                  .info { background: rgba(255, 255, 255, 0.2); padding: 15px; border-radius: 5px; margin: 10px 0; }
                  .success { color: #90EE90; font-weight: bold; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🚀 ${ProjectName} - Public Application Server</h1>
                  <p class="success">✅ Application is running successfully!</p>
                  <div class="info">
                      <h3>Instance Information:</h3>
                      <p><strong>Hostname:</strong> $(hostname)</p>
                      <p><strong>Instance ID:</strong> $(ec2-metadata --instance-id | cut -d ' ' -f 2)</p>
                      <p><strong>Private IP:</strong> $(ec2-metadata --local-ipv4 | cut -d ' ' -f 2)</p>
                      <p><strong>Public IP:</strong> $(ec2-metadata --public-ipv4 | cut -d ' ' -f 2)</p>
                      <p><strong>Availability Zone:</strong> $(ec2-metadata --availability-zone | cut -d ' ' -f 2)</p>
                  </div>
                  <div class="info">
                      <h3>Deployment Details:</h3>
                      <p><strong>Project:</strong> ${ProjectName}</p>
                      <p><strong>Stack:</strong> ${AWS::StackName}</p>
                      <p><strong>Region:</strong> ${AWS::Region}</p>
                      <p><strong>Deployed:</strong> $(date)</p>
                  </div>
                  <p>This server is deployed in a public subnet with internet access via Internet Gateway.</p>
              </div>
          </body>
          </html>
          EOF
          
          # Set proper permissions
          chmod 644 /var/www/html/index.html
          
          # Restart Apache to ensure everything is loaded
          systemctl restart httpd
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref SecGr2
            - !Ref SecGr3
          SubnetId:
            Fn::ImportValue: !Sub '${ResourcesName}-PublicSubnet-A-Id'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-Public-Instance'

  # Private Instance - Private Subnet A
  PrivateInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Ref AmazonLinux2AmiId
      KeyName: !Ref KeyPairName
      NetworkInterfaces:
        - AssociatePublicIpAddress: false
          DeviceIndex: 0
          GroupSet:
            - !Ref SecGr3
          SubnetId:
            Fn::ImportValue: !Sub '${ResourcesName}-PrivateSubnet-A-Id'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-Private-Instance'

  # DB Instance - DB Subnet A
  DbInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Ref AmazonLinux2AmiId
      KeyName: !Ref KeyPairName
      NetworkInterfaces:
        - AssociatePublicIpAddress: false
          DeviceIndex: 0
          GroupSet:
            - !Ref SecGr3
          SubnetId:
            Fn::ImportValue: !Sub '${ResourcesName}-DbSubnet-A-Id'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-DB-Instance'

Outputs:
  BastionHostId:
    Description: Bastion Host Instance ID
    Value: !Ref BastionHost
    Export:
      Name: !Sub '${AWS::StackName}-BastionHost-Id'

  BastionHostPublicIp:
    Description: Bastion Host Public IP Address
    Value: !GetAtt BastionHost.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}-BastionHost-PublicIp'

  BastionHostPublicDns:
    Description: Bastion Host Public DNS Name
    Value: !GetAtt BastionHost.PublicDnsName
    Export:
      Name: !Sub '${AWS::StackName}-BastionHost-PublicDns'

  PublicInstanceId:
    Description: Public Application Instance ID
    Value: !Ref PublicInstance
    Export:
      Name: !Sub '${AWS::StackName}-PublicInstance-Id'

  PublicInstancePublicIp:
    Description: Public Instance Public IP Address
    Value: !GetAtt PublicInstance.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}-PublicInstance-PublicIp'

  PublicInstanceUrl:
    Description: Public Application URL
    Value: !Sub 'http://${PublicInstance.PublicDnsName}'
    Export:
      Name: !Sub '${AWS::StackName}-PublicInstance-Url'

  PrivateInstanceId:
    Description: Private Instance ID
    Value: !Ref PrivateInstance
    Export:
      Name: !Sub '${AWS::StackName}-PrivateInstance-Id'

  PrivateInstancePrivateIp:
    Description: Private Instance Private IP Address
    Value: !GetAtt PrivateInstance.PrivateIp
    Export:
      Name: !Sub '${AWS::StackName}-PrivateInstance-PrivateIp'

  DbInstanceId:
    Description: DB Instance ID
    Value: !Ref DbInstance
    Export:
      Name: !Sub '${AWS::StackName}-DbInstance-Id'

  DbInstancePrivateIp:
    Description: DB Instance Private IP Address
    Value: !GetAtt DbInstance.PrivateIp
    Export:
      Name: !Sub '${AWS::StackName}-DbInstance-PrivateIp'

  SecGr1Id:
    Description: Security Group 1 ID (SSH from My IP)
    Value: !Ref SecGr1
    Export:
      Name: !Sub '${AWS::StackName}-SecGr1-Id'

  SecGr2Id:
    Description: Security Group 2 ID (HTTP/HTTPS from anywhere)
    Value: !Ref SecGr2
    Export:
      Name: !Sub '${AWS::StackName}-SecGr2-Id'

  SecGr3Id:
    Description: Security Group 3 ID (All traffic within group)
    Value: !Ref SecGr3
    Export:
      Name: !Sub '${AWS::StackName}-SecGr3-Id'
